name: Github Action Blog CMS

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:  
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: 
          - 18.x
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ${{ github.workspace }}/yarn.lock

      - run: yarn install

      - name: Build Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          run: |
          docker build \
            -t blog_cms \
            .
          docker tag blog_cms:latest nguyenvanhuan243/blog_cms:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker push nguyenvanhuan243/blog_cms:latest

      - name: Deploy to Render Server (Master)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          curl -X GET https://api.render.com/deploy/srv-cofjqbfsc6pc73fre3r0?key=Co8BORNM1vE # web service
          curl -X GET https://api.render.com/deploy/srv-cofkb3f79t8c73c5d13g?key=Zlk0AZ7lOl8 # docker container